#ifndef ENDOMORPHISM_ACTION_H
#define ENDOMORPHISM_ACTION_H
#include <sqisign_namespace.h>
#include <ec.h>
#include <quaternion.h>
#define CURVE_E0 (CURVES_WITH_ENDOMORPHISMS->curve)
#define BASIS_EVEN (CURVES_WITH_ENDOMORPHISMS->basis_even)
#define ACTION_I (CURVES_WITH_ENDOMORPHISMS->action_i)
#define ACTION_J (CURVES_WITH_ENDOMORPHISMS->action_j)
#define ACTION_K (CURVES_WITH_ENDOMORPHISMS->action_k)
#define ACTION_GEN2 (CURVES_WITH_ENDOMORPHISMS->action_gen2)
#define ACTION_GEN3 (CURVES_WITH_ENDOMORPHISMS->action_gen3)
#define ACTION_GEN4 (CURVES_WITH_ENDOMORPHISMS->action_gen4)
#define NUM_ALTERNATE_STARTING_CURVES 0
#define ALTERNATE_STARTING_CURVES (CURVES_WITH_ENDOMORPHISMS+1)
extern const curve_with_endomorphism_ring_t CURVES_WITH_ENDOMORPHISMS[1];
#endif
